In [1]:
import pandas as pd
na_values = ['NO CLUE', 'N/A', '0']
data = pd.read_csv('C:/Users/One/Downloads/Dataset/dataframe_ORGANICS/ORGANICS.csv', na_values=na_values, delimiter=',')

In [2]:
columList = data.columns.tolist()
for val in columList:
    print(data[val].value_counts())

919551      1
31263364    1
16061047    1
26897016    1
14705273    1
           ..
36957204    1
15734072    1
24522902    1
34342202    1
48858708    1
Name: ID, Length: 22223, dtype: int64
8.0     2634
7.0     2588
9.0     2584
6.0     2234
10.0    2172
11.0    1676
5.0     1662
12.0    1241
4.0      983
13.0     856
14.0     594
3.0      533
15.0     403
16.0     245
2.0      200
17.0     145
18.0      89
19.0      71
20.0      59
1.0       36
21.0      36
22.0      25
23.0      17
24.0      15
25.0      13
26.0       6
27.0       5
30.0       3
29.0       3
31.0       2
34.0       1
28.0       1
Name: DemAffl, dtype: int64
51.0    610
50.0    592
52.0    540
53.0    537
47.0    530
       ...
22.0     18
20.0     10
19.0     10
21.0      8
18.0      5
Name: DemAge, Length: 62, dtype: int64
52.0    1205
27.0     938
4.0      850
12.0     810
51.0     778
28.0     717
8.0      716
19.0     676
35.0     666
32.0     650
25.0     646
38.0     627
53.0     613
14.0     589
10.0     564
37.0     540
24.0     499
22.0     490
44.0     475
34.0     475
16.0     456
23.0     433
41.0     390
1.0      375
18.0     365
47.0     353
17.0     347
2.0      344
49.0     340
50.0     326
6.0      319
33.0     297
30.0     296
3.0      281
21.0     281
5.0      271
20.0     261
9.0      241
15.0     216
31.0     210
48.0     184
45.0     182
13.0     166
11.0     139
29.0     129
46.0     119
7.0      113
26.0     112
42.0     111
40.0      95
43.0      70
36.0      63
39.0      55
55.0      54
54.0      31
Name: DemCluster, dtype: int64
C    4566
D    4378
B    4144
F    3949
E    2608
A    1850
U      54
Name: DemClusterGroup, dtype: int64
F    12149
M     5815
U     1747
Name: DemGender, dtype: int64
South East    8634
Midlands      6741
North         4324
Scottish      1368
South West     691
Name: DemReg, dtype: int64
London          6189
Midlands        3123
S & S East      2445
N West          2096
Wales & West    1703
East            1649
Yorkshire       1443
C Scotland       836
N East           785
S West           691
N Scot           329
Ulster           266
Border           203
Name: DemTVReg, dtype: int64
Silver      8572
Tin         6487
Gold        6324
Platinum     840
Name: PromClass, dtype: int64
0.01        6487
6000.00     2232
3000.00     1425
1000.00      969
2000.00      601
            ...
20338.72       1
1105.39        1
2954.06        1
15088.81       1
2974.09        1
Name: PromSpend, Length: 2606, dtype: int64
5.0     4314
8.0     3283
4.0     2665
1.0     1722
9.0     1658
2.0     1580
7.0     1396
6.0     1140
3.0     1077
11.0     664
10.0     559
12.0     405
13.0     193
16.0     143
14.0     138
15.0     124
18.0      99
17.0      87
21.0      79
19.0      67
25.0      53
27.0      52
26.0      51
31.0      45
20.0      44
29.0      43
30.0      40
24.0      34
23.0      33
32.0      30
22.0      29
28.0      27
33.0       8
35.0       4
36.0       4
38.0       1
34.0       1
39.0       1
Name: PromTime, dtype: int64
1.0    5505
Name: TargetBuy, dtype: int64
1.0    4625
2.0     715
3.0     165
Name: TargetAmt, dtype: int64